# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="JAJAJAJA.mp3"
Content-Type: audio/mpeg

< ./JAJAJAJA.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/17e45e53-18f8-4d6f-8d6a-7aae1627ecf8/transcriptions
Content-Type: application/json

{
    "prompt": "bandeirantes, esporte"
}

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "17e45e53-18f8-4d6f-8d6a-7aae1627ecf8",
  "temperature": 0.5,
  "template": "Gere um resumo da transcrição do vídeo informada a seguir: '''{transcription}'''"
}